apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: backend-service-confidential-client
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: confidential  # Confidential access type for backend services
    clientId: backend-service-confidential
    realmId: test-realm  # Replace with your realm ID
    serviceAccountsEnabled: true  # Enable service accounts for machine-to-machine communication
    clientSecretSecretRef:
      key: client-secret
      name: backend-service-confidential-client-secret
      namespace: keycloak
  providerConfigRef:
    name: "keycloak-provider-config"
