apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: keycloak
  labels: 
    type: provider-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id":"admin-cli",
      "username": "admin",
      "password": "password",
      "url": "http://example-kc-service.keycloak:8080",
      "base_path": "",
      "realm": "master"
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-service-confidential-client-secret
data:
   client-key: Y2xpZW50a2V5MTIz
type: Opaque
