apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: user-with-password
spec:
  forProvider:
    realmId: "basic-realm"
    username: "userwithpassword"
    email: "testuser@example.com"
    emailVerified: true
    initialPassword:
      - valueSecretRef:
          key: "password"                 # Key in the secret containing the password
          name: "initial-password-secret" # Secret containing the initial password
          namespace: keycloak
        # temporary: true                   # Indicates the password is temporary
  providerConfigRef:
    name: "keycloak-provider-config"
