apiVersion: v2
name: crossplane
description: Crossplane wrapper chart
type: application
version: 0.1.0
dependencies:
  - name: crossplane
    repository: https://charts.crossplane.io/stable
    version: 1.16.0
